on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ” Create reCAPTCHA config
        run: |
          mkdir -p wp-content/themes/dotbee
          echo "<?php define('RECAPTCHA_SECRET_KEY', '${{ secrets.RECAPTCHA_SECRET_KEY }}');" > wp-content/themes/dotbee/recaptcha-config.php

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpcluster.loopia.se
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /dotbee.se/public_html/wp-content/themes/dotbee/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt
